# -*- mode: python ; coding: utf-8 -*-
import sys
from pathlib import Path

block_cipher = None

backend_dir = Path(SPECPATH)

a = Analysis(
    ['launcher.py'],
    pathex=[str(backend_dir)],
    binaries=[],
    datas=[
        ('api', 'api'),
        ('services', 'services'),
        ('models', 'models'),
        ('config.py', '.'),
        ('main.py', '.'),
        ('../frontend/dist', 'frontend_dist'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'fastapi.staticfiles',
        'fastapi.responses',
        'fastapi.routing',
        'starlette',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.staticfiles',
        'starlette.responses',
        'starlette.routing',
        'starlette.websockets',
        'pydantic',
        'pydantic_settings',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'sniffio',
        'httptools',
        'websockets',
        'websockets.legacy',
        'websockets.legacy.server',
        'watchfiles',
        'h11',
        'click',
        'email_validator',
        'cachetools',
        'tiktoken',
        'tiktoken_ext',
        'tiktoken_ext.openai_public',
        'anthropic',
        'httpx',
        'openai',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
